name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  DISPLAY: :0

jobs:
  LINUX_JOB_GCC:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install-deps
      run: sudo apt update && sudo apt install xorg openbox libglfw3 libglfw3-dev libcurl4-openssl-dev libcurl4 libxcursor-dev libxinerama-dev libxrandr-dev libcurl4-openssl-dev libxi-dev pkg-config libx11-dev

    - name: Build
      # Build your program with the given configuration
      run: ./build-linux.sh

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

  WINDOWS_JOB_MSVC:
    runs-on: windows-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v2

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Build
      # Build your program with the given configuration
      run: .\build-windows.bat

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}


