name: Codecov

on: [push, pull_request]

env:
  DISPLAY: :0

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@v4

      - name: Setup Dependencies
        run: sudo pip3 install conan && sudo apt update && sudo apt install xorg-dev openbox libxcursor-dev libxinerama-dev libxrandr-dev libxi-dev libx11-dev libgl1-mesa-dev libgl-dev

      - name: Test
        run: cd ${{github.workspace}}/coverage && make

      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          files: ${{github.workspace}}/coverage/*.c.gcov
